### ISSUE TITLE
Write CLI docs

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-cloud-client#121]
Include standard configure usage, ping example and Bash completion instructions.

**Comment by JoelPasvolsky** [comment]
http://dw-docs.readthedocs.io/en/latest/overview/dwavesys.html#dwavesys: 

![image](https://user-images.githubusercontent.com/34041130/43422769-86d505a8-93ff-11e8-9e47-0fc4aa8d0df8.png)

![image](https://user-images.githubusercontent.com/34041130/43422792-997dd70c-93ff-11e8-882a-79d193ded54e.png)

**Comment by randomir** [comment]
Alright. Note this issue was created 3 months ago.. :)
