### ISSUE TITLE
Readme ReST not rendered properly on PyPI

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-cloud-client#162]
Something broke between 0.4.0 and 0.4.1, compare:

https://pypi.org/project/dwave-cloud-client/0.4.0/
and
https://pypi.org/project/dwave-cloud-client/0.4.1/

**Comment by JoelPasvolsky** [comment]
(env) C:\Users\jpasvolsky!git_DocsOS\env\ADTT\CloudClient>python setup.py check -r -s
running check
warning: Check: missing meta-data: if 'author' supplied, 'author_email' must be supplied too
warning: Check: The project's long_description has invalid markup which will not be rendered on PyPI. The following syntax errors were detected:
**line 31: Error: Unknown interpreted text role "term".**
error: Please correct your package.

(env) C:\Users\jpasvolsky!git_DocsOS\env\ADTT\CloudClient>python setup.py check -r -s
running check
warning: Check: missing meta-data: if 'author' supplied, 'author_email' must be supplied too
**The project's long description is valid RST.**
error: Please correct your package.
