### ISSUE TITLE
Enable results download by problem ID

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-cloud-client#186]
For old/out-of-context problems, referred by ID, enable futures to be recreated and results downloaded. Something like this, but user-friendly:
```
>>> from dwave.cloud.computation import Future
>>> from dwave.cloud import Client
>>> c = Client.from_config()
>>> s = c.get_solver()
>>> 
>>> f = Future(s, '85fa54d1-0055-46f0-9f45-e8b99a9d857e', False, {})
>>> 
>>> c._load(f)
>>> f.done()
True
>>> f.result()
{'samples': [[-1, 0, 0, ....
```

**Comment by arcondello** [comment]
I'd like to take a crack at this. I gather that the block is that (right now) problem decoding is solver-specific. Some potential approaches:

A) Put the method on the solver:
```
>>> f = s.get_problem('85fa54d1-0055-46f0-9f45-e8b99a9d857e')
```
which side-steps the issue of coupled solver/decoding by forcing the user to specify.

B) Put the method on the client and use `Solver.id` as a unique identifier
```
>>> f = c.get_problem('85fa54d1-0055-46f0-9f45-e8b99a9d857e', s.id)
```
By making the solver id the second argument it will allow easy future deprecation.


I also noticed that `Future.id` is non-blocking and may be `None`, it might be good to have a blocking version of that, maybe `f.get_id()`

**Comment by arcondello** [comment]
Ah, I read the REST-API [docs](https://docs.dwavesys.com/docs/latest/c_rest_api_3.html#get-problem) more closely and see that from just the `problem_id`, it is possible to get the solver name, making both (A) and (B) redundant. Making the best option...

C) Just the `problem_id`
```
>>> f = c.get_problem('85fa54d1-0055-46f0-9f45-e8b99a9d857e')
```
Still doesn't look like _too_ invasive a change, though obviously much more than the 3-line methods that would support (A) and (B).
