### ISSUE TITLE
Config file write by CLI fails on Windows

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-cloud-client#197]
(env) C:\Users\jp...\dwave-ocean-sdk>dwave config create
Configuration file not found; the default location is: C:\Users\jp...\dwave\dwave.conf
Confirm configuration file path (editable):
Profile (create new): default
API endpoint URL (editable): https:...
Authentication token (editable): DWV-b7...
Client class (qpu or sw): qpu
Solver (can be left blank): DW_2...
Proxy URL (can be left blank):
Error writing to configuration file: [Errno 22] invalid mode ('w') or filename: ''

I see in the code:

try:
        with open(config_file, 'w') as fp:
            config.write(fp)
    except Exception as e:
        click.echo("Error writing to configuration file: {}".format(e))
        return 2

And I see that on my Windows OS, 

```
In [2]: file = open("C:\Users\jp...dwave-ocean-sdk\dwave.conf","w")
In [3]: file.write("Hello World")
In [4]: file.close()
In [5]: file = open("C:\Users\jp...dwave-ocean-sdk\dwave\dwave.conf","w")
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-5-5e7e89a01188> in <module>()
----> 1 file = open("C:\Users\jp...dwave-ocean-sdk\dwave\dwave.conf","w")
IOError: [Errno 2] No such file or directory: 'C:\\Users\\jp...dwave-ocean-sdk\\dwave\\dwave.conf'
```

So I suspect that the OS is not allowing dwave to create a new directory in the open command as part of the file name.

**Comment by randomir** [comment]
@JoelPasvolsky, as assumed, readline-powered editable input on windows/mac didn't work correctly. Switched to simpler default-provided method. Maybe docs/examples need updating?
