### ISSUE TITLE
dwave ping: local variable 'timing' referenced before assignment

### ISSUE THREAD

**Issue by igable** [dwavesystems/dwave-cloud-client#264]
It appears in some timeout situations `dwave ping` will attempt to output some timing variables outside of try block that may not be defined. The error message in that case is:

    local variable 'timing' referenced before assignment

**Comment by randomir** [comment]
Can you check which version of `dwave` tools are you using? It might be we already fixed that. Try running:
```
dwave --version
```

**Comment by igable** [comment]
We were running 0.4.10. I think the commit you posted will fix it.  Because we should no longer execute:

https://github.com/dwavesystems/dwave-cloud-client/blob/master/dwave/cloud/cli.py#L249

In this scenario.
