### ISSUE TITLE
Annealing_time in range creates error that appears to be on server side

### ISSUE THREAD

**Issue by schnorea** [dwavesystems/dwave-cloud-client#296]
Hello,
Have run into an issue where I submit a sampling request and get back an error indicating that annealing_time the parameters is out of range when I don't think it is based on the annealing_time_range property.  Additionally the error trace shows a in equality that looks odd.  If I back off the annealing time this problem goes away but I am not sure why.

Here is a short piece of code and the resulting stack trace.  The version of the code this came from isn't the current version but because I think the issue may be on the server it may still be relevent.

According to properties `annealing_time_range => [1, 2000]`

So when I run:
```
from dimod import BinaryQuadraticModel
from dimod import BINARY
from dwave.system.samplers import DWaveSampler
from dwave.system.composites import EmbeddingComposite

annealing_time = 1000

h = {'a': -1., 'b': 2}
J = {('a', 'b'): 1.5}
offset = 1

q_sampler = EmbeddingComposite(DWaveSampler())
bqm = BinaryQuadraticModel(h,J,offset,BINARY)
response = q_sampler.sample(bqm,
                          num_reads = 5000,
                          chain_strength = 2,
                          chain_break_fraction = True,
                          annealing_time = annealing_time)

```
I get this:
```
Traceback (most recent call last):
  File "time_range_test.py", line 24, in <module>
    annealing_time = annealing_time)
  File "/usr/local/lib/python2.7/dist-packages/dwave/system/composites/embedding.py", line 228, in sample
    response = child.sample(bqm_embedded, **parameters)
  File "/usr/local/lib/python2.7/dist-packages/dimod/core/sampler.py", line 194, in sample
    response.change_vartype(Vartype.BINARY, energy_offset=offset)
  File "/usr/local/lib/python2.7/dist-packages/dimod/decorators.py", line 178, in new_f
    return f(*final_args, **final_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dimod/sampleset.py", line 647, in change_vartype
    self.record.energy = self.record.energy + energy_offset
  File "/usr/local/lib/python2.7/dist-packages/dimod/sampleset.py", line 433, in record
    self._resolve_future()
  File "/usr/local/lib/python2.7/dist-packages/dimod/sampleset.py", line 336, in _resolve_future
    samples = self._result_hook(self._future)
  File "/usr/local/lib/python2.7/dist-packages/dwave/system/samplers/dwave_sampler.py", line 420, in _hook
    result = computation.result()
  File "/usr/local/lib/python2.7/dist-packages/dwave/cloud/computation.py", line 493, in result
    self._load_result()
  File "/usr/local/lib/python2.7/dist-packages/dwave/cloud/computation.py", line 658, in _load_result
    six.reraise(*self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/dwave/cloud/client.py", line 909, in _handle_problem_status
    raise SolverFailureError(message['error_msg'])
dwave.cloud.exceptions.SolverFailureError: Upper limit on user-specific timing-related parameters exceeded: 5001000 > 1000000
```

**Comment by randomir** [comment]
Hi @schnorea! The error message is not too informative, but the explanation is pretty simple.

Namely, the [total problem runtime](https://docs.dwavesys.com/docs/latest/c_solver_1.html#problem-run-duration-range) must be within [`problem_run_duration_range`](https://docs.dwavesys.com/docs/latest/c_solver_1.html#problem-run-duration-range).

The upper limit for the solver you were submitting was 1000000 μs (1 second), and the total problem duration was:
```
duration = (annealing_time + readout_thermalization) * num_reads + programming_thermalization
```
When you plug in 5000 reads and 1000 μs anneal time, with default [`programming_thermalization`](https://docs.dwavesys.com/docs/latest/c_solver_1.html#programming-thermalization) = [`default_programming_thermalization`](https://docs.dwavesys.com/docs/latest/c_solver_1.html#default-programming-thermalization) = 1000 μs, and [`readout_thermalization`](https://docs.dwavesys.com/docs/latest/c_solver_1.html#readout-thermalization) = [`default_readout_thermalization`](https://docs.dwavesys.com/docs/latest/c_solver_1.html#default-readout-thermalization) 0 μs:
```
duration = (1000 + 0) * 5000 + 1000 = 5001000
```
