### ISSUE TITLE
Simplify 'config create' step

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-cloud-client#304]
Since for a default Leap user we require only API token, and all other prompts may confuse some (i.e. config path, profile name, endpoint, solver, client), we might consider splitting the "config create" flow in two branches: (1) default/basic; and (2) advanced.

In the advanced branch we can then also add a few more non-essential parameter prompts (e.g. timeout values).

Seems like one config issue users reported so far is related to config file path (if user changes the path while not understanding the consequences). Implicitly using a default there (in basic branch) will help. Use of the default (undefined) solver is also strongly encouraged (because undefined solver is translated to `{"online": True}`. That addressed the problem of hard-coding solver names too (as older versions of client did).

**Comment by conta877** [comment]
ooh this would mean re-doing all 3 videos!! 🙀

**Comment by randomir** [comment]
Oh, in that case we won't change our user interface ever. :smile:

**Comment by conta877** [comment]
thats the spirit! :P

**Comment by randomir** [comment]
But now seriously, I opened this issue to actually get some feedback on the idea.

We got feedback from our training folks that some users are struggling with this config step. /cc @JoelGottlieb @vgoliber
