### ISSUE TITLE
dwave CLI: Improve error message when no solvers found

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-cloud-client#316]
```
$dwave solvers
Solver(s) None not found.
```

**Comment by randomir** [comment]
The error you're seeing is probably caused by #315.

The error message is probably fine, but for some reason `None` was interpreted as solver name. Which could be a bug in the code, or in your config file.

**Comment by JoelPasvolsky** [comment]
Yes, "None was interpreted as solver name" was what I wanted to flag here
