### ISSUE TITLE
Home-Based Config Paths

### ISSUE THREAD

**Issue by ccoffrin** [dwavesystems/dwave-cloud-client#318]
It seems that at least on OS X the config file paths cannot include home-based paths.  For example, `~/foo/my.conf` or `$HOME/foo/my.conf`.  If it is easy to support these it would provide some added convenience.

**Comment by randomir** [comment]
Isn't `~/Library/Application Support/dwave` supported?

You can double check with:
```
$ dwave config ls -m
```

**Comment by ccoffrin** [comment]
Let me clarify.  In this library the call `load_config("~/foo/my.conf")` does not seem to work.  The problem seems to be that the special character `~` is not expanded before trying to open the file.

**Comment by randomir** [comment]
Oh, that is a bug. Will fix. Thanks!
