### ISSUE TITLE
No solver found with specified couplings

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-cloud-client#320]
Example of `get_solvers` function has `couplings__issuperset=[[0,128], [0,4]]` but ```sampler = DWaveSampler(solver={'qpu': True, 'couplings__issuperset': [0,4]})``` gives ```SolverNotFoundError: Solver with the requested features not available``` despite such a sampler being available:
```
sampler = DWaveSampler(solver={'qpu': True})
sampler.edgelist[:5]
Out[18]: [(0, 4), (0, 5), (0, 6), (0, 7), (0, 128)]  
```
I do not see `couplings` defined as a derived property, However, I do see a solver property `couplers`---was maybe your intention an example such as ```sampler = DWaveSampler(solver={'qpu': True, 'couplers__issuperset': [(0,4)]})``` and the `couplings` a mistake (it is used for dwave CLI)?

**Comment by randomir** [comment]
Good catch, @JoelPasvolsky. Just use `couplers`. I've fixed the example.
