### ISSUE TITLE
Accept FileView-serializable BQMs in Solver.upload_bqm

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-cloud-client#343]
If BQM supports streaming, `Solver.upload_bqm(bqm)` should be identical to `Solver.upload_bqm(FileView(bqm))`.

**Comment by arcondello** [comment]
One issue is that there is no way (at the moment) to tell whether a bqm can be used with a FileView other than to try. An obvious solution would be to add `BQM.to_fileview()`, or to just try it once FileView supports all bqm types.

Also the preferred syntax for the file views is with a context manager.
```
with FileView(bqm) as fv:
    Solver.upload_bqm(fv)
```
See https://github.com/dwavesystems/dimod/issues/580

**Comment by randomir** [comment]
@arcondello, I believe the right approach would be something like this https://github.com/dwavesystems/dimod/issues/599.
