### ISSUE TITLE
'hybrid_v1' solver is not available on version 0.7.0

### ISSUE THREAD

**Issue by amikw** [dwavesystems/dwave-cloud-client#371]
Before I tried to use the new hybrid solver, I checked available solvers using `dwave solvers` command. I could not find 'hybrid_v1' on version 0.7.0:

```
$ dwave --version
D-Wave Cloud Client, version 0.7.0

$ dwave solvers --list
DW_2000Q_5
DW_2000Q_VFYC_5
```

However, when I downgraded dwave-cloud-client to v. 0.6.3, 'hybrid_v1' was listed on available solvers:
```
$ dwave --version
D-Wave Cloud Client, version 0.6.3

$ dwave solvers --list
DW_2000Q_5
DW_2000Q_VFYC_5
hybrid_v1
```

**Comment by randomir** [comment]
Looks like you have constrained the `client` to `qpu`, or the `solver` to QPU-based in your `dwave.conf`.

You can verify this by running `dwave solvers --list --all`.

Try removing `client = qpu` from your config. That way a generic, non-QPU specific client will be used.

**Comment by amikw** [comment]
Thank you so much! I could find the 'hybrid_v1' solver when I commented out `client = qpu`:
```$ dwave --version
D-Wave Cloud Client, version 0.7.0
$ dwave solvers --list --all
DW_2000Q_5
DW_2000Q_VFYC_5
hybrid_v1
```

My `dwave.conf` was
```
[defaults]
endpoint = https://***
token = ***

[first-available-qpu]
client = qpu
```
and removed the last line.
