### ISSUE TITLE
Prefer higher versioned hybrid solvers with feature based solver selection

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dwave-cloud-client#395]
```
>>> from dwave.cloud import Client
>>> solver = Client.from_config().get_solver(hybrid=True)
```
should prefer the solver with the highest
```
>>> solver.properties['version']
'1.0'
```
Alternative would be to just handle this in [LeapHybridSampler](https://github.com/dwavesystems/dwave-system/blob/2315092628ac7bee1d4e8c5619449689796ba0fb/dwave/system/samplers/leap_hybrid_sampler.py#L105), something like
```
>>> solver = client.get_solver(hybrid=True, order_by='-version')
```

**Comment by arcondello** [comment]
I am actually inclined to go with the alternative (just doing it in LeapHybridSampler), but thought I should open the discussion.

**Comment by randomir** [comment]
I would go with the alternative.

The default `order_by="avg_load"` tries to balance the load (within the group of solvers that satisfy all constraints/features).

Changing that to prefer version, but only for hybrid solvers, seems unintuitive.
