### ISSUE TITLE
Unexpected behavior in order_by

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dwave-cloud-client#401]
```
>>> from dwave.cloud import Client
>>> client = Client.from_config(solver=dict(qpu=True))
>>> client.get_solver()
StructuredSolver(id='DW_2000Q_6')
>>> client.get_solver(order_by='-num_active_qubits')
UnstructuredSolver(id='hybrid_v1')
>>> client.get_solver(order_by='-num_active_qubits', qpu=True)
StructuredSolver(id='DW_2000Q_6')
```
I would have expected to see `StructuredSolver(id='DW_2000Q_6')` in all three examples, given `client = Client.from_config(qpu=True)`

**Comment by randomir** [comment]
That's a bug, good catch.

(Reason: `order_by` is treated as a filter in `get_solver` && "default solver" is used only if no filters are given. Easy fix.)
