### ISSUE TITLE
Expose reformatted parameters

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dwave-cloud-client#465]
The [`StructuredSolver._format_params`](
https://github.com/dwavesystems/dwave-cloud-client/blob/b008a3276bdfa091584563a591c5eb8f0f0f94f2/dwave/cloud/solver.py#L950) method currently transforms the `initial_state` parameter from a dict to the format expected by the endpoint.

This translation, while useful for the user, makes it hard for other libraries (e.g. [aws-braket-ocean-plugin](https://github.com/aws/amazon-braket-ocean-plugin-python)) that are trying to mock the behavior of the `DWaveSampler` from [dwave-system](https://github.com/dwavesystems/dwave-system) to do so.

It would be helpful to expose this logic in a way that can be used by other libraries. Some possible approaches:
1) Change the `_format_params` method to a public class method, or even a static method. This would allow users/libaries to use the method without needing to authenticate with D-Wave.
2) Move `_format_parmas` to the `DWaveSampler` level, and expose it as a public method. We would likely want to deprecate the method in the cloud-client.

I am inclined towards (2).

**Comment by JoelPasvolsky** [comment]
2 makes sense to me given that the transformation is specific to QPU. Where would it live in 1? Also I think with 1 it would need renaming, but that may be true for 2 also

**Comment by randomir** [comment]
Keeping this particular function in the cloud client makes sense to me. Why? Because it translates a nice state map into a list with 3's - very SAPI-specific, low-level and ugly.

This is related to #166 and #199.

I'd say, ideally, we don't use SAPI-specific data encoding anywhere on the client's API surface, and the translation happens internally.
