### ISSUE TITLE
Possible typo on lines 417 & 420

### ISSUE THREAD

**Issue by adam-douglass** [dwavesystems/dwave-cloud-client#5]
Looks like there is an extra 'not' in the logic that is preventing dates from being passed through.

**Comment by randomir** [comment]
Based on fd86de8a2a5968dab6ce0a70b771526335255494, lines 417/420 are lines 507 and 510 in current master (c3406606eb31b04cab8a56e570bf79165034b639):

https://github.com/dwavesystems/dwave-cloud-client/blob/c3406606eb31b04cab8a56e570bf79165034b639/dwave/cloud/client.py#L507

https://github.com/dwavesystems/dwave-cloud-client/blob/c3406606eb31b04cab8a56e570bf79165034b639/dwave/cloud/client.py#L510
