### ISSUE TITLE
dwave ping should fail with param missing error rather than hanging, if an HSS solver is selected by default

### ISSUE THREAD

**Issue by vpapish** [dwavesystems/dwave-cloud-client#511]
**Steps:**
1. Enter command "dwave ping"
2. Need to be in the case where an hss solver is chosen as the default solver 

**Actual Outcome:**
User gets output similar to:
`Using endpoint: https://na-west-1.cloud.dwavesys.com/sapi/v2/`
`Using region: na-west-1`
`Using solver: hybrid_binary_quadratic_model_version2p`
then the program hangs and must be manually terminated. 

**Expected output:**
Program completes successfully or fails with a missing parameter error.

**Comment by randomir** [comment]
Hey @vpapish, thank you for reporting this. Would you be able to provide details about your environment (OS, python)? Thanks!
