### ISSUE TITLE
REST SAPI Question, what does 'offset' mean in the 'Problem' object?

### ISSUE THREAD

**Issue by almosnow** [dwavesystems/dwave-cloud-client#527]
Hello guys/gals,

I am playing around with your API and I'm truly enjoying it,

Being a very meticulous person, I always inspect all the data I get/post from the services I use,

When manually parsing the JSON object that comes with the data, I see the usual format, quad and lin fields (I'm using https://docs.dwavesys.com/docs/latest/c_rest_api_5.html as reference), but I also see an offset property there which seems to contain a float and which does not appears to be in the documentation.

Could you shed some light into what is this?

Thanks.

**Comment by randomir** [comment]
That's a great catch, @almosnow!

Solver API indeed does not support problem `offset`, as defined by [BQM](https://docs.ocean.dwavesys.com/en/stable/docs_dimod/reference/quadratic.html#binary-quadratic-models) (or QM in general). So, to support BQMs in Ocean, we are temporarily keeping the offset on computation (Future) only, not actually transmitting to (or storing in) SAPI.

In summary, it's a (known) issue we need to fix. :slightly_smiling_face:  https://github.com/dwavesystems/dwave-cloud-client/blob/a1d4a9e76b007b5604428173277602549b443d2b/dwave/cloud/computation.py#L157

**Comment by almosnow** [comment]
Thanks @randomir, mistery solved! 😃 

>That's a great catch, @almosnow!

I appreciate that, there's some other things I've found here and there (I'm basically dismantling your whole API in order to learn), but I'll open separate issues as needed.

Cheers!

**Comment by randomir** [comment]
@almosnow -- bug reports welcome, pull requests appreciated! :laughing:

**Comment by almosnow** [comment]
@randomir

>pull requests appreciated

I would be willing to help you extend your documentation a little bit, from the pov of someone who is not really a QC scientist but an experienced developer nonetheless. Would that work for you guys?

Best :)

**Comment by randomir** [comment]
Absolutely, we welcome contributions! Thanks!

**Comment by almosnow** [comment]
Nice,

I wouldn't mind extending the docs a little bit,

For instance, the content at -> https://docs.dwavesys.com/docs/latest/doc_rest_api.html

How may I contribute on that? (I couldn't find a public repo w/ the docs)

**Comment by randomir** [comment]
@almosnow, that page is part of System Docs, and it's not open sourced yet.

@JoelPasvolsky is the owner of those docs, so best to coordinate with him. Joel, if I remember correctly, you're considering open-sourcing parts of System Docs?

**Comment by JoelPasvolsky** [comment]
Thank you for calling our attention to this, @almosnow. 
We recently opened an internal ticket to do some extensive reworking of the SAPI REST guide, which is not open source, and appreciate your input. Please let us know of any problems or suggestions you might have.
Thank you!
