### ISSUE TITLE
dwave.cloud.exceptions.SolverFailureError: Internal SAPI Error

### ISSUE THREAD

**Issue by gumix97** [dwavesystems/dwave-cloud-client#571]
Hi everyone, 

I got this error message when sending a problem to DWave's Leap Hybrid CQM Sampler. Any clues on what could be happening / who is the system admin?

```
File "C:\Python\Python380\lib\site-packages\dimod\sampleset.py", line 1505, in aggregate
    _, indices, inverse = np.unique(self.record.sample, axis=0,
  File "C:\Python\Python380\lib\site-packages\dimod\sampleset.py", line 1121, in record
    self.resolve()
  File "C:\Python\Python380\lib\site-packages\dimod\sampleset.py", line 1470, in resolve
    samples = self._result_hook(self._future)
  File "C:\Python\Python380\lib\site-packages\dwave\cloud\computation.py", line 823, in <lambda>
    self, lambda f: f.wait_sampleset())
  File "C:\Python\Python380\lib\site-packages\dwave\cloud\computation.py", line 755, in wait_sampleset
    result = self._load_result()
  File "C:\Python\Python380\lib\site-packages\dwave\cloud\computation.py", line 893, in _load_result
    raise self._exception
  File "C:\Python\Python380\lib\site-packages\dwave\cloud\client\base.py", line 1460, in _handle_problem_status
    raise SolverFailureError(errmsg)
dwave.cloud.exceptions.SolverFailureError: Internal SAPI Error (reference # - 0366380f-0950-4ff2-afb9-e569f8a3aba4). Contact System Administrator

```

Thank you!

**Comment by randomir** [comment]
Hi @gumix97, this seems to be an internal error (or perhaps a bug) on server side. We'll look into it and get back to you.

In the meantime, if you have a [code to reproduce it](https://stackoverflow.com/help/mcve), and can share it, that would be great. If you share the code, maybe we'll be able to suggest a workaround to unblock you in short term.

**Comment by randomir** [comment]
@gumix97, looks like forward slashes (`/`) in constraint labels are not handled properly, and that's causing this issue.

Until we fix this, a temporary workaround is to avoid the use of slashes in your constraint labels (during CQM formulation).

**Comment by gumix97** [comment]
Hi @randomir, thank you for your response. Does it include every way to express a division (**(-1),...) or only the slashes? I've been trying with other expressions and I unfortunately still get the same error.

**Comment by randomir** [comment]
@gumix97, you can still use whatever (supported) operator in your expression -- just don't include `/` in your constraint names.

For example, **don't do this**:
```
>>> cqm = dimod.CQM()
...
>>> cqm.add_constraint(..., label='a/b')
>>>                                 ^ this is problematic
```
Not sure how exactly you formulate your problem, but if you're generating constraint names automatically, e.g. from some dataset of labels, check you don't have slashes in that dataset.

**Comment by gumix97** [comment]
Thank you @randomir! I will review al the code to see if there are still any slashes going unnoticed.
