### ISSUE TITLE
Circular reference in `Computation.wait_sampleset()` causes slow garbage collection in some cases

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dwave-cloud-client#601]
https://github.com/dwavesystems/dwave-cloud-client/blob/5829a538b2045c9fac1bec7fe7888feb6973945d/dwave/cloud/computation.py#L795-L799

creates a circular reference. This means that the garbage collector is slow to identify and remove the sampleset/computation.

You can see this with
```python
from dwave.system import DWaveSampler

sampler = DWaveSampler()

s = 0
for i in range(1000):
    print("job:", i)
    future = sampler.solver.sample_ising({30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0}, {}, num_reads=1000)
    sampleset = future.wait_sampleset()
```
where (tested with Python 3.12) you can watch slowly accumulating memory usage, whereas
```python
import gc
from dwave.system import DWaveSampler

sampler = DWaveSampler()

s = 0
for i in range(1000):
    print("job:", i)
    future = sampler.solver.sample_ising({30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0}, {}, num_reads=1000)
    sampleset = future.wait_sampleset()
    gc.collect()
```
and
```python
from dwave.system import DWaveSampler

sampler = DWaveSampler()

s = 0
for i in range(1000):
    print("job:", i)
    future = sampler.solver.sample_ising({30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0}, {}, num_reads=1000)
    sampleset = future.wait_sampleset()
    del sampleset.wait_id
```
hold steady.

**Comment by arcondello** [comment]
I think it would suffice to just do
```python
        id_ = self.wait_id()
        sampleset.wait_id = lamda: id_
```
instead.

**Comment by randomir** [comment]
The first line is an overkill indeed. Response is resolved at the beginning of `wait_sampleset()`, so `id` is known already (it's in `self.id`), and `wait_id()` returns without blocking. To prevent capturing `self` in `lambda`'s closure, your proposed approach should work.

However, the bigger problem is in the `sampleset` property:

https://github.com/dwavesystems/dwave-cloud-client/blob/5829a538b2045c9fac1bec7fe7888feb6973945d/dwave/cloud/computation.py#L822-L828

where sampleset is not resolved yet and `wait_id` indeed needs to block.

The second part of your snippet, where we store sampleset on computation is needed, in the current code at least. It's used to cache constructed samplesets, but also makes `.result()` consistent on qpu and hybrid solvers (which return sampleset as part of the response). It seems a bigger refactor will be needed here to remove all circular references.

**Comment by arcondello** [comment]
Agree that the unresolved case is tougher and might require a bigger refactor. We could make accessing the `.sampleset` property block on the completion of `wait_id()`. Probably for most use cases that would be fine :thinking:
