### ISSUE TITLE
Wrong default path for Windows

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-cloud-client#81]
>>> from dwave.cloud.config import get_default_configfile_path
>>> print(get_default_configfile_path())
C:\Users\jpasvolsky\AppData\Local\dwavesystem\dwave\dwave.conf

(There is an extra "\dwavesystem\" between Local and dwave.)

According to dwave.cloud.config.load_config_from_file(filename=None):
On Windows, config file should be located in: C:\Users\<username>\AppData\Local\dwave\client\dwave.conf

**Comment by randomir** [comment]
Thanks! Docs weren't up to date.
